Bump/0.26
OpenSourcePolitics/decidim-antibes pull request #16
Opened 2023-03-01 13:58 UTC by eliegaboriau

2023-03-01 18:39 UTC, armandfardeau approved these changes

2023-03-03 10:20 UTC, paulinebessoles requested changes
Thank you for the PR @eliegaboriau ! 
Could you check that registration form works well with the address API call? I couldn't register. 

Email header and footer also should be white. 

<img width="594" alt="Capture d’écran 2023-03-03 à 11 15 32" src="https://user-images.githubusercontent.com/52420208/222695192-31128229-6fb9-41a5-9910-4d92d98b2deb.png">

2023-03-03 12:15 UTC, paulinebessoles approved these changes

2023-03-03 12:16 UTC, eliegaboriau commented
The address should now works.
The email should work with new mails.

2023-03-03 12:29 UTC, merged