Bump/0.26 (#16)
OpenSourcePolitics/decidim-antibes pull request #17
Opened 2023-03-03 15:09 UTC by paulinebessoles

2023-03-06 09:58 UTC, armandfardeau requested changes
Hello thanks for your contribution !

Could you please fix the failing CI workflow?

2023-03-06 18:11 UTC, paulinebessoles commented
Good catch @armandfardeau, those CD files shouldn't have been backported from the decidim-app! I deleted them.

2023-03-08 15:16 UTC, armandfardeau approved these changes

2023-03-09 11:23 UTC, eliegaboriau approved these changes

2023-03-13 13:52 UTC, merged